services:
  db:
    container_name: db_postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
